### ISSUE TITLE
Load Image: Error: CanvasPlus: Image load failed, error in mask image with imported url

### ISSUE THREAD

**Issue by tiavina-mika** [jhuckaby/canvas-plus#11]
The remote image is not loaded with mask. The image is from google

```
canvas.mask({
   image: 'https://storage.googleapis.com/template-preprod-ojhfeisoax/template-preprod-ojhfeisoax_7964a4c5028041c1ace61ecb6ba4a7d5_y7zw2mu12r.png',
});
```

**Comment by jhuckaby** [comment]
This is not a bug.  From the docs:

> The source can be another CanvasPlus object, a native HTML5 Canvas object, or a native Image object.

https://github.com/jhuckaby/canvas-plus#mask

You cannot give it a URL, it has to be a pre-loaded image object or another canvas.
