### ISSUE TITLE
Pango warning couldn't load font

### ISSUE THREAD

**Issue by Omega-dev0** [jhuckaby/canvas-plus#16]
When running in node js on windows:
```
canvas.text({
                    "text": "Test",
                    "font": "./assets/gothicb.ttf",
                    "size": 70,
                    "color": "#ffffff",
                    "gravity": "center",
                    "offsetX": 50,
                    "offsetY": 120
                });
```

I am getting this error:
`Pango-WARNING : couldn't load font "pixl0996a41a3817491eaa4b0ff3a70fbbad Not-Rotated 70px", falling back to "Sans Not-Rotated 70px", expect ugly output.`

this error pops up for each line with canvas.text but I am never using this "pixl0996a41a3817491eaa4b0ff3a70fbbad" font, is there a fix to this?

**Comment by jhuckaby** [comment]
Hmm, for some reason Pango (the underlying library that [node-canvas](https://github.com/Automattic/node-canvas) uses to load and render fonts) really doesn't like your `gothicb.ttf` file.  I think this is *probably* because it's a TrueType font and you are on Windows.  You might need to convert it to OTF (OpenType).  Do you have other fonts you can try?

The `pixl0996a41a3817491eaa4b0ff3a70fbbad` thing is just an auto-generated CSS font name based on the file path.

**Comment by Omega-dev0** [comment]
Tried with the same font in otf and with a different font in both in ttf and otf and the error remain the same.
I did not mention it because I thought it was not related but when launching the program I am also getting the following error:

`GLib-GIO-WARNING **: 18:41:54.644: Unexpectedly, UWP app `BluskySoftwareInc.17062EE08491F_2.2.3.0_x86__61yk12x6sxn40' (AUMId `BluskySoftwareInc.17062EE08491F_61yk12x6sxn40!audacity') supports 52 extensions but has no verbs`
This seems to be related to audacity.

**Comment by jhuckaby** [comment]
What a strange issue.  You'll have to forgive me, as I don't have a Windows PC here, so I can't really reproduce the problem.  I can say that canvas-plus relies **heavily** on the [node-canvas](https://github.com/Automattic/node-canvas) module, which does all of the heavy lifting behind the scenes, including font loading.  That's the module that loads Pango, and the one throwing this error.

I think we need to come up with a simple script that reproduces the issue, using node-canvas directly (not canvas-plus per se), and if you get the same error, possibly [create an issue over on their repo](https://github.com/Automattic/node-canvas/issues/new).  Something like this perhaps:

```js
var fs = require('fs');
var Canvas = require('canvas');

Canvas.registerFont('assets/gothicb.ttf', { family: 'GothicB' });

var canvas = Canvas.createCanvas(640, 100);
var ctx = canvas.getContext('2d');
var text = 'Now is the time for all good men.';

ctx.font = 'normal normal 36px GothicB';
ctx.fillText(text, 10, 35);

canvas.createPNGStream().pipe(fs.createWriteStream('output.png'));
```

**Comment by Omega-dev0** [comment]
Just found the issues:
It seems that the font was not correctly loading with `canvas.loadFont(  )`
Re-installed the font on windows and it worked.
Thanks
