### ISSUE TITLE
[Browser] Failed to load image: Unsupported or unknown file type

### ISSUE THREAD

**Issue by shady-ladow** [jhuckaby/canvas-plus#2]
I have this error when I try to put a file (file path, blob or array buffer) in load() function. The function load() only work with url. My file is a picture in .png.

[ERROR][load] CanvasPlus: Failed to load image: Unsupported or unknown file type
Uncaught Error: CanvasPlus: Failed to load image: Unsupported or unknown file type
    at __construct.doError (canvas-plus.js:4146)
    at __construct.load (canvas-plus.js:282)
    at FileReader.fileReader.onload (canvas-plus.js:254)

**Comment by jhuckaby** [comment]
Can you provide some sample code and your PNG image to help me reproduce this?

**Comment by shady-ladow** [comment]
``` javascript
const canvas = new CanvasPlus()
let format = 'png'
, mode = 'fit'
canvas.set('debug', true)
canvas.load('chat.png', (err) => {
        if (err) throw err //get error here
        //code
        canvas.write({ format, quality: 100 }, (error, buf) => {
           if (error) throw err
           const blob = new Blob([buf], { type: `image/${format}` })
           , object_url = URL.createObjectURL(blob)
           , img = new Image()
           img.src = object_url
           document.getElementById('preview').innerHTML = ''
           document.getElementById('preview').appendChild(img)
    })
})
```

![chat](https://user-images.githubusercontent.com/19528365/64765081-c4a23280-d543-11e9-9ed8-0ae0385aa7cc.png)

Canvas.load works with url but it doesn't work with image name, blob or array buffer.

**Comment by jhuckaby** [comment]
I do apologize, but I honestly cannot reproduce this issue.  I took your code and image verbatim, and threw them up on my server, and it all works great:

https://pixlcore.com/temp/cpp-bug-test/index.html

No errors, and the debug log looks exactly as I would expect.  I tested in the latest Safari, Chrome and Firefox.

**Comment by shady-ladow** [comment]
I am using Chrome. Why picture is loading from url ? My picture is a locale file.

Thank you

![image](https://user-images.githubusercontent.com/19528365/64944866-9720f600-d86f-11e9-9595-8e7847cfabb9.png)

**Comment by jhuckaby** [comment]
Chrome is a web browser, so it cannot load arbitrary files from your local PC.  It runs in a special sandbox to prevent that kind of thing.  The only way to load a local file is for the user (you) to upload it by clicking a file upload field.

Check out the canvas-plus playground app to see how it handles this: https://jhuckaby.github.io/canvas-plus-playground/

<img width="247" alt="Screen_Shot_2019-09-16_at_11_44_49_AM" src="https://user-images.githubusercontent.com/700765/64984353-85dbe780-d877-11e9-82a7-facd687aebc0.png">

Sorry for the confusion.

**Comment by shady-ladow** [comment]
I don't know why it didn't work. (I forgot sorry) but it was my fault
