### ISSUE TITLE
RGB filter

### ISSUE THREAD

**Issue by JosefHjorth** [jhuckaby/canvas-plus#3]
Hi! Looks like an amazing library. Just tried the node js version out a bit. 

I was just wondering if it's possible to run a RGB filter? I.e. setting the image to red 255 offset, and leaving the rest at 0 {255, 0, 0}? Or any other combination.

Best regards,

Josef

**Comment by jhuckaby** [comment]
Hi there!  Thanks a lot.  Well, I believe you can achieve what you are asking using a **curve**:

https://github.com/jhuckaby/canvas-plus#curves

Here is a live demo showing a +100 offset to the red channel:

https://jhuckaby.github.io/canvas-plus-playground/?t=load/eyJpbWFnZSI6IndhdGVyZmFsbC5qcGcifQ%3D%3D&t=resize/eyJ3aWR0aCI6NjQwLCJoZWlnaHQiOjQ4MCwibW9kZSI6ImZpdCJ9&t=curves/eyJwb2ludHMiOlsxMDAsMTg3LDI1NSwyNTVdLCJjaGFubmVscyI6InIifQ%3D%3D&f=png

You can make the curve more "exact" by using specific X/Y 2D curve points:

```js
var CanvasPlus = require('pixl-canvas-plus');
var canvas = new CanvasPlus();

canvas.load( 'waterfall.jpg', function(err) {
	if (err) throw err;

	canvas.resize({
		"width": 640,
		"height": 480,
		"mode": "fit"
	});

	canvas.curves({
		"red": [
			[0, 100],
			[155, 255],
			[255, 255]
		]
	});

	canvas.write({"format":"png"}, function(err, buf) {
		if (err) throw err;

		// 'buf' will be a binary buffer containing final image...
		require('fs').writeFileSync('my_image.png', buf);
	});

});
```

Good luck!

**Comment by JosefHjorth** [comment]
Thanks for your help! Btw. which javascript framework are you using on the demo page?

**Comment by jhuckaby** [comment]
You bet!

The demo playground actually doesn't use a framework per se, it's just cobbled together using jQuery 😊
